#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## My Bombyx
## File description:
## main file
##

import sys

def my_boucle1(n, k):
    if k < 1 or k > 4:
        return (84)
    x = float(n)
    print("%d %.2f" %(1, n))
    for i in range(1, 100):
        x = x * k * (1000.0 - x) / 1000.0
        print("%d %.2f" %(i + 1, x))
    return (0)

def my_boucle2(n, i0, i1):
    if i0 < 0 or i1 < i0:
        return (84)
    k = 1.0
    while k <= 4.0:
        x = float(n)
        for i in range(1, i0):
            x = x * k * (1000.0 - x) / 1000.0
        for i in range(i0, i1 + 1):
            print("%.2f %.2f" %(k, x))
            x = x * k * (1000.0 - x) / 1000.0
        k += 0.01
    return (0)
    
if len(sys.argv) == 3:
    try:
        sys.exit(my_boucle1(int(sys.argv[1]), float(sys.argv[2])))
    except:
        sys.exit(84)
elif len(sys.argv) == 4:
    try:
        sys.exit(my_boucle2(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])))
    except Exception as e:
        print(e)
        sys.exit(84)
elif len(sys.argv) == 2 and sys.argv[1] == "-h":
    print ("USAGE\n    ./106bombyx n [k | i0 i1]\n\nDESCRIPTION\n    n       number of first generation individuals\n    k       growth rate from 1 to 4\n    i0      initial generation (included)\n    i1      final generation (included)\n")
    sys.exit(0)
else:
    sys.exit(84)
